---
extends:
  - airbnb-typescript
  - prettier
  - prettier/react
plugins:
  - prettier
  - react-hooks

rules:
  '@typescript-eslint/camelcase': 0
  react/react-in-jsx-scope: 0
  react/jsx-props-no-spreading: 0
  no-console: 2

parserOptions:
  project: './tsconfig.json'
